### ISSUE TITLE
how can i get a static gif by gifski?

### ISSUE THREAD

**Issue by onanana** [ImageOptim/gifski#222] opened 2022-03-01 17:41 UTC
im using cli version in windows 10.

gifski printed a error
only a single image file was given as an input, this is not enough to make an aniation.

Cant i get a static gif image by gifski?

**Comment by andylizi** [comment] 2022-03-01 17:42
Duplicate of #178

**Comment by kornelski** [comment] 2022-03-01 21:15
Please don't use GIF for still images. It's a rubbish format. Use 8-bit PNG instead.

**Closed** 2022-03-01 21:15 UTC
